-- Bronxville Natural Market — committed Supabase schema
-- Apply with `supabase db push` or the SQL editor. Do not rely on dashboard-only DDL.
-- Admin bootstrap (service role / SQL editor only — never from the app):
--   insert into public.user_roles (user_id, role)
--   values ('00000000-0000-4000-a000-000000000099', 'admin')
--   on conflict (user_id) do update set role = 'admin';

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;
create extension if not exists citext;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

-- ── Catalog ────────────────────────────────────────────────────────────────

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  logo_url text,
  logo_alt text,
  official_website_url text,
  logo_use_status text not null default 'permission_pending',
  logo_background text not null default 'cream',
  is_featured boolean not null default false,
  display_order integer not null default 0,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  parent_id bigint references public.categories(id),
  description text,
  display_order integer not null default 0,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.brands(id),
  category_id bigint not null references public.categories(id),
  subcategory_id bigint references public.categories(id),
  name text not null,
  slug text not null unique,
  short_description text,
  long_description text,
  form text,
  size text,
  count integer,
  flavor text,
  strength_value numeric(12,3),
  strength_unit text,
  sku text not null unique,
  upc text,
  regular_price_cents integer not null check (regular_price_cents >= 0),
  sale_price_cents integer check (sale_price_cents is null or sale_price_cents >= 0),
  availability text not null default 'in_stock',
  is_featured boolean not null default false,
  is_bestseller boolean not null default false,
  is_new boolean not null default false,
  is_active boolean not null default true,
  is_archived boolean not null default false,
  archived_at timestamptz,
  vegan boolean not null default false,
  vegetarian boolean not null default false,
  organic boolean not null default false,
  gluten_free boolean not null default false,
  soy_free boolean not null default false,
  dairy_free boolean not null default false,
  alcohol_free boolean not null default false,
  non_gmo boolean not null default false,
  sugar_free boolean not null default false,
  kosher boolean not null default false,
  halal boolean not null default false,
  search_aliases text,
  ingredient_highlights text,
  usage_text text,
  warnings text,
  is_demo boolean not null default false,
  source_url text,
  source_type text,
  image_use_status text,
  verification_status text not null default 'unverified',
  approval_status text not null default 'approved',
  product_line text,
  certifications text,
  price_is_demo boolean not null default true,
  search_document tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  label text not null,
  sku text not null unique,
  form text,
  size text,
  count integer,
  strength_value numeric(12,3),
  strength_unit text,
  regular_price_cents integer,
  sale_price_cents integer,
  availability text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  alt_text text,
  display_order integer not null default 0,
  is_primary boolean not null default false,
  image_use_status text,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  kind text not null default 'wellness',
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_tags (
  product_id bigint not null references public.products(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (product_id, tag_id)
);

create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  discount_percent integer,
  is_active boolean not null default true,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promotion_products (
  promotion_id bigint not null references public.promotions(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  primary key (promotion_id, product_id)
);

create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  store_name text not null default 'Bronxville Natural Market',
  phone text,
  phone_is_placeholder boolean not null default true,
  email text,
  address_line1 text not null default '86 Pondfield Rd',
  city text not null default 'Bronxville',
  state text not null default 'NY',
  zip text not null default '10708',
  hours_note text,
  announcement text,
  pickup_instructions text,
  delivery_note text,
  min_order_cents integer not null default 0,
  currency text not null default 'USD',
  timezone text not null default 'America/New_York',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.products_search_document()
returns trigger language plpgsql as $$
begin
  new.search_document :=
    setweight(to_tsvector('simple', coalesce(new.name, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(new.sku, '') || ' ' || coalesce(new.upc, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(new.search_aliases, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(new.ingredient_highlights, '')), 'C') ||
    setweight(to_tsvector('simple', coalesce(new.short_description, '')), 'D');
  return new;
end;
$$;

drop trigger if exists trg_products_search on public.products;
create trigger trg_products_search
before insert or update on public.products
for each row execute function public.products_search_document();

create index if not exists products_search_idx on public.products using gin (search_document);
create index if not exists products_name_trgm on public.products using gin (name gin_trgm_ops);
create index if not exists products_sku_trgm on public.products using gin (sku gin_trgm_ops);
create index if not exists products_upc_trgm on public.products using gin (upc gin_trgm_ops);

-- ── Users ──────────────────────────────────────────────────────────────────

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique,
  display_name text,
  first_name text,
  last_name text,
  avatar_url text,
  phone text,
  profile_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.customer_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text,
  recipient_name text not null,
  phone text,
  address_line1 text not null,
  address_line2 text,
  city text not null,
  state text not null,
  postal_code text not null,
  country_code text not null default 'US',
  delivery_instructions text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists customer_addresses_one_default
  on public.customer_addresses (user_id) where is_default;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  base text;
  uname text;
  n int := 0;
begin
  base := lower(regexp_replace(split_part(coalesce(new.email, 'user'), '@', 1), '[^a-z0-9]+', '', 'g'));
  if length(base) < 3 then base := 'user'; end if;
  uname := base;
  while exists (select 1 from public.profiles where username = uname) loop
    n := n + 1;
    uname := base || n::text;
  end loop;
  insert into public.profiles (id, username, display_name, first_name, last_name, profile_completed)
  values (
    new.id,
    uname,
    coalesce(new.raw_user_meta_data->>'full_name', uname),
    coalesce(new.raw_user_meta_data->>'given_name', ''),
    coalesce(new.raw_user_meta_data->>'family_name', ''),
    false
  );
  insert into public.user_roles (user_id, role) values (new.id, 'customer');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.prevent_role_escalation()
returns trigger language plpgsql as $$
begin
  if tg_op = 'UPDATE' and new.role is distinct from old.role then
    if auth.role() is distinct from 'service_role' then
      raise exception 'Role changes require a privileged migration or service-role script';
    end if;
  end if;
  if tg_op = 'INSERT' and new.role = 'admin' and auth.role() is distinct from 'service_role' then
    raise exception 'Admin bootstrap requires a privileged migration or service-role script';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_user_roles_no_escalation on public.user_roles;
create trigger trg_user_roles_no_escalation
before insert or update on public.user_roles
for each row execute function public.prevent_role_escalation();

-- ── Commerce ───────────────────────────────────────────────────────────────

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  public_token text not null unique default encode(gen_random_bytes(12), 'hex'),
  order_number text not null unique,
  user_id uuid references auth.users(id) on delete set null,
  fulfillment_type text not null check (fulfillment_type in ('pickup', 'delivery')),
  status text not null default 'placed',
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  delivery_address_line1 text,
  delivery_address_line2 text,
  delivery_city text,
  delivery_state text,
  delivery_zip text,
  delivery_country text,
  delivery_instructions text,
  payment_method text not null default 'pay_at_pickup',
  payment_status text not null default 'unpaid',
  currency text not null default 'USD',
  stripe_checkout_session_id text,
  stripe_payment_intent_id text,
  subtotal_cents integer not null,
  delivery_fee_cents integer,
  total_cents integer not null,
  notes text,
  is_demo boolean not null default true,
  placed_at timestamptz not null default now(),
  paid_at timestamptz,
  cancelled_at timestamptz,
  idempotency_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  product_name text not null,
  brand_name text,
  sku text,
  unit_price_cents integer not null,
  quantity integer not null,
  line_total_cents integer not null
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null,
  provider_checkout_session_id text,
  provider_payment_intent_id text,
  status text not null,
  amount_cents integer not null,
  currency text not null default 'USD',
  idempotency_key text unique,
  paid_at timestamptz,
  failure_code text,
  failure_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  provider_event_id text not null unique,
  event_type text not null,
  payload_hash text not null,
  processing_status text not null default 'received',
  attempt_count integer not null default 0,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  last_error text
);

create table if not exists public.idempotency_keys (
  key text primary key,
  request_hash text not null,
  resource_type text,
  resource_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text,
  request_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  channel text not null,
  payload_summary text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

-- updated_at
do $$
declare t text;
begin
  foreach t in array array['brands','categories','products','product_variants','tags','promotions','store_settings','profiles','customer_addresses','orders','payments']
  loop
    execute format('drop trigger if exists trg_%s_updated on public.%I', t, t);
    execute format('create trigger trg_%s_updated before update on public.%I for each row execute function public.set_updated_at()', t, t);
  end loop;
end $$;

-- ── RLS ────────────────────────────────────────────────────────────────────

alter table public.brands enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_images enable row level security;
alter table public.tags enable row level security;
alter table public.product_tags enable row level security;
alter table public.promotions enable row level security;
alter table public.promotion_products enable row level security;
alter table public.store_settings enable row level security;
alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.payment_events enable row level security;
alter table public.idempotency_keys enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.notification_outbox enable row level security;

-- Catalog public read
create policy brands_public_read on public.brands for select using (true);
create policy categories_public_read on public.categories for select using (true);
create policy products_public_read on public.products for select using (is_active and not is_archived);
create policy product_images_public_read on public.product_images for select using (
  exists (select 1 from public.products p where p.id = product_id and p.is_active and not p.is_archived)
);
create policy tags_public_read on public.tags for select using (true);
create policy product_tags_public_read on public.product_tags for select using (true);
create policy promotions_public_read on public.promotions for select using (is_active);
create policy store_settings_public_read on public.store_settings for select using (true);

-- Admin catalog writes
create policy brands_admin_write on public.brands for all using (public.is_admin()) with check (public.is_admin());
create policy categories_admin_write on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy products_admin_all on public.products for all using (public.is_admin()) with check (public.is_admin());
create policy product_images_admin_all on public.product_images for all using (public.is_admin()) with check (public.is_admin());
create policy tags_admin_all on public.tags for all using (public.is_admin()) with check (public.is_admin());
create policy promotions_admin_all on public.promotions for all using (public.is_admin()) with check (public.is_admin());
create policy store_settings_admin_upd on public.store_settings for update using (public.is_admin());

-- Profiles / roles / addresses
create policy profiles_own_select on public.profiles for select using (id = auth.uid());
create policy profiles_own_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy user_roles_own_select on public.user_roles for select using (user_id = auth.uid());
create policy addresses_own_all on public.customer_addresses for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Orders: customers see own; cannot change payment/price fields via this policy (updates denied)
create policy orders_own_select on public.orders for select using (user_id = auth.uid());
create policy orders_own_insert on public.orders for insert with check (user_id = auth.uid());
create policy orders_admin_all on public.orders for all using (public.is_admin()) with check (public.is_admin());
create policy order_items_own_select on public.order_items for select using (
  exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
);
create policy order_items_admin_all on public.order_items for all using (public.is_admin()) with check (public.is_admin());

-- Payments, events, audit, idempotency: no anon/authenticated policies (service role only)
revoke all on public.payments from anon, authenticated;
revoke all on public.payment_events from anon, authenticated;
revoke all on public.admin_audit_logs from anon, authenticated;
revoke all on public.idempotency_keys from anon, authenticated;
revoke all on public.user_roles from anon, authenticated;
grant select on public.user_roles to authenticated;
