-- Durable, server-priced order requests. There is intentionally no online
-- payment path in this schema. Browser/customer roles cannot write totals.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  public_token text not null unique default replace(gen_random_uuid()::text, '-', ''),
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  fulfillment_type text not null check (fulfillment_type in ('pickup', 'delivery')),
  status text not null default 'placed'
    check (status in ('placed', 'confirmed', 'preparing', 'ready_for_pickup', 'out_for_delivery', 'completed', 'cancelled')),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  delivery_address_line1 text,
  delivery_address_line2 text,
  delivery_city text,
  delivery_state text,
  delivery_zip text,
  delivery_instructions text,
  payment_method text not null default 'call_store' check (payment_method = 'call_store'),
  payment_status text not null default 'unpaid' check (payment_status = 'unpaid'),
  currency text not null default 'USD' check (currency = 'USD'),
  subtotal_cents integer not null check (subtotal_cents >= 0),
  delivery_fee_cents integer,
  total_cents integer not null check (total_cents >= 0),
  notes text,
  is_demo boolean not null default false,
  placed_at timestamptz not null default now(),
  cancelled_at timestamptz,
  idempotency_key uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, idempotency_key)
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  brand_name text,
  sku text,
  unit_price_cents integer not null check (unit_price_cents >= 0),
  quantity integer not null check (quantity between 1 and 99),
  line_total_cents integer not null check (line_total_cents >= 0),
  created_at timestamptz not null default now()
);

create index if not exists orders_user_created_idx
  on public.orders (user_id, created_at desc);

create index if not exists orders_status_created_idx
  on public.orders (status, created_at desc);

create index if not exists order_items_order_idx
  on public.order_items (order_id);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- All customer and administrator access goes through authenticated Next.js
-- route handlers. The service role is kept in server-only code and the route
-- handlers enforce ownership/admin authorization before querying these tables.
revoke all on public.orders from public, anon, authenticated;
revoke all on public.order_items from public, anon, authenticated;
grant select, insert, update, delete on public.orders to service_role;
grant select, insert, update, delete on public.order_items to service_role;
grant usage, select on sequence public.orders_id_seq to service_role;
grant usage, select on sequence public.order_items_id_seq to service_role;

create or replace function public.submit_order_request(
  p_user_id uuid,
  p_idempotency_key uuid,
  p_fulfillment_type text,
  p_customer_name text,
  p_customer_phone text,
  p_delivery_address_line1 text,
  p_delivery_address_line2 text,
  p_delivery_city text,
  p_delivery_state text,
  p_delivery_zip text,
  p_delivery_instructions text,
  p_items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_existing_id bigint;
  v_order_id bigint;
  v_customer_email text;
  v_item jsonb;
  v_line jsonb;
  v_product_id uuid;
  v_quantity integer;
  v_product_name text;
  v_brand_name text;
  v_sku text;
  v_availability text;
  v_regular_price integer;
  v_sale_price integer;
  v_sale_starts_at timestamptz;
  v_sale_ends_at timestamptz;
  v_unit_price integer;
  v_subtotal bigint := 0;
  v_lines jsonb := '[]'::jsonb;
  v_has_duplicates boolean;
begin
  select email into v_customer_email
  from auth.users
  where id = p_user_id;

  if v_customer_email is null then
    raise exception using errcode = '22023', message = 'A verified customer account is required.';
  end if;

  select id into v_existing_id
  from public.orders
  where user_id = p_user_id and idempotency_key = p_idempotency_key;

  if v_existing_id is not null then
    return v_existing_id;
  end if;

  if p_fulfillment_type not in ('pickup', 'delivery') then
    raise exception using errcode = '22023', message = 'Choose store pickup or local delivery.';
  end if;
  if length(trim(coalesce(p_customer_name, ''))) not between 2 and 160 then
    raise exception using errcode = '22023', message = 'Customer name is required.';
  end if;
  if length(trim(coalesce(p_customer_phone, ''))) not between 5 and 40 then
    raise exception using errcode = '22023', message = 'A valid phone number is required.';
  end if;
  if p_fulfillment_type = 'delivery' and (
     length(trim(coalesce(p_delivery_address_line1, ''))) not between 2 and 240
     or length(trim(coalesce(p_delivery_city, ''))) not between 2 and 120
     or length(trim(coalesce(p_delivery_state, ''))) not between 2 and 40
     or length(trim(coalesce(p_delivery_zip, ''))) not between 3 and 20
  ) then
    raise exception using errcode = '22023', message = 'A complete address is required.';
  end if;
  if jsonb_typeof(p_items) is distinct from 'array'
     or jsonb_array_length(p_items) = 0
     or jsonb_array_length(p_items) > 50 then
    raise exception using errcode = '22023', message = 'The cart must contain between 1 and 50 products.';
  end if;

  select count(*) <> count(distinct item.value ->> 'product_id')
  into v_has_duplicates
  from jsonb_array_elements(p_items) as item(value);
  if v_has_duplicates then
    raise exception using errcode = '22023', message = 'The cart contains a duplicate product.';
  end if;

  for v_item in select value from jsonb_array_elements(p_items) as item(value)
  loop
    if coalesce(v_item ->> 'product_id', '') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
       or jsonb_typeof(v_item -> 'quantity') is distinct from 'number'
       or coalesce(v_item ->> 'quantity', '') !~ '^[0-9]+$' then
      raise exception using errcode = '22023', message = 'A cart item is invalid.';
    end if;

    v_product_id := (v_item ->> 'product_id')::uuid;
    v_quantity := (v_item ->> 'quantity')::integer;
    if v_quantity not between 1 and 99 then
      raise exception using errcode = '22023', message = 'Product quantities must be between 1 and 99.';
    end if;

    select
      p.name,
      b.name,
      variant.sku,
      variant.availability,
      variant.regular_price_cents,
      variant.sale_price_cents,
      variant.sale_starts_at,
      variant.sale_ends_at
    into
      v_product_name,
      v_brand_name,
      v_sku,
      v_availability,
      v_regular_price,
      v_sale_price,
      v_sale_starts_at,
      v_sale_ends_at
    from public.products p
    join public.brands b on b.id = p.brand_id
    join lateral (
      select pv.*
      from public.product_variants pv
      where pv.product_id = p.id and pv.is_active = true
      order by pv.is_default desc, pv.display_order asc, pv.created_at asc
      limit 1
    ) as variant on true
    where p.id = v_product_id and p.status = 'active';

    if not found then
      raise exception using errcode = '22023', message = 'A product in the cart is no longer available.';
    end if;
    if v_availability not in ('in_stock', 'low_stock', 'special_order') then
      raise exception using errcode = '22023', message = format('%s is not currently available to order.', v_product_name);
    end if;

    v_unit_price := case
      when v_sale_price is not null
       and v_sale_price < v_regular_price
       and (v_sale_starts_at is null or v_sale_starts_at <= now())
       and (v_sale_ends_at is null or v_sale_ends_at > now())
      then v_sale_price
      else v_regular_price
    end;
    v_subtotal := v_subtotal + (v_unit_price::bigint * v_quantity);
    if v_subtotal > 2147483647 then
      raise exception using errcode = '22023', message = 'The order total is too large.';
    end if;

    v_lines := v_lines || jsonb_build_array(jsonb_build_object(
      'product_id', v_product_id,
      'product_name', v_product_name,
      'brand_name', v_brand_name,
      'sku', v_sku,
      'unit_price_cents', v_unit_price,
      'quantity', v_quantity,
      'line_total_cents', v_unit_price * v_quantity
    ));
  end loop;

  insert into public.orders (
    order_number,
    user_id,
    fulfillment_type,
    customer_name,
    customer_email,
    customer_phone,
    delivery_address_line1,
    delivery_address_line2,
    delivery_city,
    delivery_state,
    delivery_zip,
    delivery_instructions,
    subtotal_cents,
    total_cents,
    idempotency_key
  ) values (
    'PENDING-' || replace(gen_random_uuid()::text, '-', ''),
    p_user_id,
    p_fulfillment_type,
    trim(p_customer_name),
    lower(v_customer_email),
    trim(p_customer_phone),
    nullif(trim(p_delivery_address_line1), ''),
    nullif(trim(p_delivery_address_line2), ''),
    nullif(trim(p_delivery_city), ''),
    nullif(trim(p_delivery_state), ''),
    nullif(trim(p_delivery_zip), ''),
    nullif(trim(p_delivery_instructions), ''),
    v_subtotal::integer,
    v_subtotal::integer,
    p_idempotency_key
  )
  on conflict (user_id, idempotency_key) do nothing
  returning id into v_order_id;

  if v_order_id is null then
    select id into v_order_id
    from public.orders
    where user_id = p_user_id and idempotency_key = p_idempotency_key;
    return v_order_id;
  end if;

  update public.orders
  set order_number = 'BNM-' || to_char(current_date, 'YYMMDD') || '-' || lpad(v_order_id::text, 6, '0')
  where id = v_order_id;

  for v_line in select value from jsonb_array_elements(v_lines) as line(value)
  loop
    insert into public.order_items (
      order_id,
      product_id,
      product_name,
      brand_name,
      sku,
      unit_price_cents,
      quantity,
      line_total_cents
    ) values (
      v_order_id,
      (v_line ->> 'product_id')::uuid,
      v_line ->> 'product_name',
      nullif(v_line ->> 'brand_name', ''),
      nullif(v_line ->> 'sku', ''),
      (v_line ->> 'unit_price_cents')::integer,
      (v_line ->> 'quantity')::integer,
      (v_line ->> 'line_total_cents')::integer
    );
  end loop;

  return v_order_id;
end;
$$;

revoke all on function public.submit_order_request(
  uuid, uuid, text, text, text, text, text, text, text, text, text, jsonb
) from public, anon, authenticated;

grant execute on function public.submit_order_request(
  uuid, uuid, text, text, text, text, text, text, text, text, text, jsonb
) to service_role;

comment on function public.submit_order_request(
  uuid, uuid, text, text, text, text, text, text, text, text, text, jsonb
) is 'Atomically creates an unpaid call-to-confirm order request using current database prices.';
